public class devpracticeTest {
    
 /*   public testmethod static void method12() {
        Account acc = new Account(Name='raj',phone='123');
       // Account acc1 = new Account(Name='abc',phone='234');
        List<Account> acclist = new List<Account>();
        acclist.add(acc);
       // acclist.add(acc1);
        Insert acclist;
        //List<Contact> conlist = new List<Contact>();
        
         // Account acc =new Account();
          //acc.name='rak ';
          //acc.phone='123';
           //insert acc;
           
       /* for (Account acc2 : acclist){
            
            if(acc.phone=='123'){
       Contact con = new Contact();
          con.AccountId= acc2.Id;
          con.LastName=acc2.Name;
            con.phone=acc2.Phone;
          conlist.add(con) ;
            }}
          insert conlist;
        
          Test.StartTest();
          devpractice.method(acclist);
      
          Test.StopTest();
        
        
      
    } */
}