@IsTest
public class MyIterableTest {
   /* @IsTest
    static void testIterableForLoop (){
        List<String> strings = new List<String>{'Hello','world'};
            MyIterable MyIterableInstance = new MyIterable(strings);
        
        System.debug('Running the for loop..');
        for(String str : MyIterableInstance){
            System.debug('String:' + str); 
        }
    } */
    
     @IsTest
    static void testIterableForLoop() {
        List<String> strings = new List<String>{'Hello', 'World'};
        MyIterable myIterableInstance = new MyIterable(strings);
        
        for (String str : myIterableInstance) {
            System.debug('String: ' + str);
        }
    }

}